### ISSUE TITLE
clarification on `nodeDataChannel.cleanup()` 

### ISSUE THREAD

**Issue by harbu** [murat-dogan/node-datachannel#108]
Hi there!

We're looking to implement clean up properly in the Streamr Network project with my colleague @teogeb. 

We have a few questions on how the `nodeDataChannel.cleanup()`  method should be invoked and how it affects the lifecycle of the library.

- From what we understand, it should be called when we no longer have open connections or connections occurring?
- After calling the method, can we still use the library later on to form connections? E.g. say we form some connections, exchange some data, and then close those connections. If in the same process later on we want to use the library again to open some connections, can we do so, if we have already called `cleanup()`  before?

**Comment by paullouisageneau** [comment]
`nodeDataChannel.cleanup()` makes the library stop internal threads and unload resources, it should be called only if your are finished with connections.

You are correct `nodeDataChannel.cleanup()` should be used when you no longer need any connection, as it will close any connection that is still open. It is cleaner but not mandatory to close all data channels and peer connections yourself first.

Even after calling `nodeDataChannel.cleanup()`, you may indeed reuse the library later and open connections again, libdatachannel will simply reload everything necessary. However, it makes more sense to call `nodeDataChannel.cleanup()` only once at the end of your program or test file, since calling it multiple times will just force useless unload-reload cycles.

**Comment by harbu** [comment]
> `nodeDataChannel.cleanup()` makes the library stop internal threads and unload resources, it should be called only if your are finished with connections.
> 
> You are correct `nodeDataChannel.cleanup()` should be used when you no longer need any connection, as it will close any connection that is still open. It is cleaner but not mandatory to close all data channels and peer connections yourself first.
> 
> Even after calling `nodeDataChannel.cleanup()`, you may indeed reuse the library later and open connections again, libdatachannel will simply reload everything necessary. However, it makes more sense to call `nodeDataChannel.cleanup()` only once at the end of your program or test file, since calling it multiple times will just force useless unload-reload cycles.

Thanks that helps! :+1:

**Comment by murat-dogan** [comment]
Hi,
Thanks @paullouisageneau for super clarification.
I prefer to call `nodeDataChannel.cleanup()` just before the process exit OR if I know I will not need `nodeDataChannel` lib again.
