### ISSUE TITLE
Error connection aborted

### ISSUE THREAD

**Issue by DarePhoenix** [murat-dogan/node-datachannel#111]
Hello, when I load my page, the client connect to 4 differents servers, do some checks, then disconnect from all the servers, and connect to a new server.

But some peoples actually facing this issue :

![image](https://user-images.githubusercontent.com/86203108/169580639-d2100c3f-7cad-4d3c-bdd9-9447b7afda21.png)

I don't know when it's happening, because it works perfectly fine for me, but don't work randomly for some peoples (if it don't work one time, it never work)

Any idea ? (I'm using node-datachannel v3.1 via geckos.io)

**Comment by paullouisageneau** [comment]
This is unrelated to node-datachannel. The issue is that HTTP requests to the geckos.io servers fail at the network level because the connections fail to open, so it should be reported to geckos.io.

Anyway, the connection could be blocked by a filter, firewall, or proxy on the user side. It might be triggered by the HTTPS service running on port 8080 instead of the expected port 443.

**Comment by DarePhoenix** [comment]
okey !

**Comment by DarePhoenix** [comment]
> This is unrelated to node-datachannel. The issue is that HTTP requests to geckos.io servers fail at network level because the connections fail to open, so it should be reported to geckos.io.
> 
> Anyway, the connection could be blocked by a filter, firewall, or proxy on the user side. It might be triggered by the HTTPS service running on port 8080 instead of the expected port 443.

okey I ask
