### ISSUE TITLE
The PC page cannot be displayed properly

### ISSUE THREAD

**Issue by Canees** [murat-dogan/node-datachannel#124]
I'm sorry I'm here again，I've tried a lot of things and it still doesn't work，

@paullouisageneau Dear Paul, do you have any suggestions?
![image](https://user-images.githubusercontent.com/40012261/180355619-6f68d71b-a454-4be4-a8d2-07c6970463a2.png)

![image](https://user-images.githubusercontent.com/40012261/180355304-10b56276-b896-4ea5-936e-81eeba90b234.png)

![image](https://user-images.githubusercontent.com/40012261/180355357-eefc53e6-187e-4e47-819a-5fa4bbde0c57.png)

**Comment by paullouisageneau** [comment]
It looks like there is an SSRC mismatch: the media description specifies 42 as SSRC while gstreamer outputs a random one and you don't override it in the JS forwarding loop (like it is done the C++ code). You should add `ssrc=42` to the gstreamer pipeline: `rtph264pay pt=96 mtu=1200 ssrc=42`.

Additionally, `RtcpReceivingSession` is for handling RTCP feedback when you receive a stream, not when you send one like here, you should remove it.

What does the C++ code correspond to? Also, please paste formatted code instead of posting screen captures, it is easier to read.

**Comment by Canees** [comment]
> It looks like there is an SSRC mismatch: the media description specifies 42 as SSRC while gstreamer outputs a random one and you don't override it in the JS forwarding loop (like it is done the C++ code). You should add `ssrc=42` to the gstreamer pipeline: `rtph264pay pt=96 mtu=1200 ssrc=42`.
> 
> Additionally, `RtcpReceivingSession` is for handling RTCP feedback when you receive a stream, not when you send one like here, you should remove it.
> 
> What does the C++ code correspond to? Also, please paste formatted code instead of posting screen captures, it is easier to read.

Thank you Paul, it's already working. I'm new to video and I only have a rough idea of what C++ means. I thought it needed some special treatment.
